version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

commands:
  deploy_to_s3:
    steps:
      - attach_workspace:
          at: ~/repo
      - aws-cli/install
      - run:
          name: Deploy to S3
          command: aws s3 sync --acl public-read dist/ s3://neoguide.pl --delete
  clear_cloud_front_cache:
    steps:
      - attach_workspace:
          at: ~/repo
      - aws-cli/install
      - run:
          name: Clear CloudFront
          command: aws cloudfront create-invalidation --distribution-id=E1SB75D1JR73QZ --paths /

executors:
  node_defaults:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.13.0-stretch

  python_defaults:
    working_directory: ~/repo
    docker:
      - image: circleci/python:2.7-jessie

jobs:
  checkout_code:
    executor: node_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  build_statics:
      executor: node_defaults
      steps:
        - attach_workspace:
            at: ~/repo
        - restore_cache:
            name: Restore NPM Package Cache
            keys:
              - v1-npm-deps-{{ checksum "package-lock.json" }}
        - run: npm install
        - save_cache:
            name: Save NPM Package Cache
            key: v1-npm-deps-{{ checksum "package-lock.json" }}
            paths:
              - ~/.cache/npm
        - run: npm run build
        - persist_to_workspace:
            root: ~/repo
            paths:
              - dist

  deploy:
      executor: python_defaults
      steps:
        - attach_workspace:
            at: ~/repo
        - aws-cli/install
        - aws-cli/configure:
            aws-access-key-id: STAGING_AWS_ACCESS_KEY_ID
            aws-secret-access-key: STAGING_AWS_SECRET_ACCESS_KEY
            aws-region: STAGING_AWS_DEFAULT_REGION
        - deploy_to_s3
        - clear_cloud_front_cache

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - build_statics:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build_statics
          # filters:
          #   branches:
          #     only: master